"use client"

import { Quicksand } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import { Provider } from "react-redux";
import { store } from "@/store/store";
import { Toaster } from "react-hot-toast";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
});

// export const metadata = {
//   title: "Nest E-Commerce",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} antialiased`}>
        <Provider store={store}> {children}</Provider>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
